name: Codespace

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.18

      - name: Install dependencies & AWS CLI
        run: |
          pip install awscli
